apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-client
  namespace: metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-client
  template:
    metadata:
      labels:
        app: spring-client
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
    spec:
      containers:
      - name: spring-client
        image: spring-client:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: spring-client
  namespace: metric
spec:
  type: ClusterIP
  selector:
    app: spring-client
  ports:
  - port: 8080
    name: app
    targetPort: 8080
  - port: 9464
    name: metric
    targetPort: 9464

