app:
  name: spring-server
  namespace: server

# Deployment 설정
replicaCount: 1

image:
  repository: spring-server
  tag: latest
  pullPolicy: Never

# Service 설정
service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9464
      targetPort: 9464

env:
  - name: OTEL_SERVICE_NAME
    value: "test-server"
  - name: OTEL_PROPAGATORS
    value: "tracecontext,baggage,b3"
  - name: OTEL_RESOURCE_ATTRIBUTES
    value: "service.name=test-server"

podAnnotations:
  instrumentation.opentelemetry.io/inject-java: "otel/otel-instrumentation"
