# Prometheus 서버 비활성화 (가장 중요)
prometheus:
  enabled: false

# Alertmanager 비활성화
alertmanager:
  enabled: false

# Grafana 비활성화
grafana:
  enabled: false

# 기타 메트릭 수집기 비활성화
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false