
prometheus:
  enabled: false
alertmanager:
  enabled: false
grafana:
  enabled: false

defaultRules:
  create: false

coreDns:
  enabled: false
kubelet:
  enabled: false
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false


kube-state-metrics:
  enabled: false
  prometheus:
    monitor:
      enabled: false

prometheus-node-exporter:
  enabled: false
  prometheus:
    monitor:
      enabled: false

prometheusOperator:
  serviceMonitor:
    enabled: false