# grafana/values-test.yaml

adminPassword: "admin"

service:
  type: LoadBalancer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        # ▼▼▼▼▼ 이 부분이 추가되었습니다 ▼▼▼▼▼
        jsonData:
          # 보낼 헤더의 이름을 정의합니다.
          httpHeaderName1: "X-Scope-OrgID"
        # ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
      # ▼▼▼▼▼ 이 부분이 추가되었습니다 ▼▼▼▼▼
      # jsonData에 정의된 헤더의 실제 값을 여기에 안전하게 저장합니다.
      # 이 값은 쿠버네티스 시크릿으로 관리됩니다.
        secureJsonData:
          httpHeaderValue1: "fake" # 테스트용 단일 테넌트이므로 "fake"와 같은 임의의 ID를 사용합니다.
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    apm-dashboard:
      file: grafana/dashboard.json