deploymentMode: SimpleScalable

loki:
  # 기존 useTestSchema 대신 명시적 schema 설정 (replication 오류 해결)
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # 컴포넌트별 세부 설정 추가
  ingester:
    chunk_encoding: snappy
    # 기존 read-only 파일 시스템 오류 해결
    wal:
      enabled: true
      dir: /var/loki/wal
    chunk_target_size: 1048576
    chunk_block_size: 262144

  querier:
    max_concurrent: 4

  pattern_ingester:
    enabled: true

  # replication factor 명시적 설정 (기존 오류 해결)
  commonConfig:
    replication_factor: 1

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 7d
    ingestion_rate_mb: 5
    ingestion_burst_size_mb: 10
    max_entries_limit_per_query: 5000
    max_cache_freshness_per_query: 10m
    max_query_length: 168h
    max_query_parallelism: 16
    max_streams_per_user: 1000
    max_line_size: 128KB
    reject_old_samples: true
    reject_old_samples_max_age: 24h
    # replication factor 추가 설정
    replication_factor: 1

  # 기존 S3 설정 유지
  storage:
    type: 's3'
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-ruler"
      admin: "loki-admin"
    s3:
      endpoint: "http://minio.minio.svc.cluster.local:9000"
      insecure: true
      accessKeyId: "minioadmin"
      secretAccessKey: "minioadmin123"
      s3ForcePathStyle: true

# 컴포넌트 설정 (기존 1 replica 유지하되 권한 문제 해결)
backend:
  enabled: true
  replicas: 1
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    runAsGroup: 10001

read:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    runAsGroup: 10001

write:
  enabled: true
  replicas: 1
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    runAsGroup: 10001

# 기존 MinIO 설정 유지
minio:
  enabled: true

# Gateway 서비스 타입 추가 (연결 문제 해결)
gateway:
  enabled: true
  service:
    type: ClusterIP  # 내부 클러스터 사용이므로 ClusterIP 권장
    port: 80
  nginxConfig:
    # 기존 502 오류 해결을 위한 timeout 설정
    resolver: "kube-dns.kube-system.svc.cluster.local"
    httpSnippet: |
      client_max_body_size 100m;
      proxy_read_timeout 300s;
      proxy_connect_timeout 300s;
      proxy_send_timeout 300s;

# 기존 설정 유지
chunksCache:
  enabled: false

# 다른 배포 모드 컴포넌트 비활성화 (기존 설정 유지)
distributor:
  enabled: false
  replicas: 0

ingester:
  enabled: false
  replicas: 0

querier:
  enabled: false
  replicas: 0

queryFrontend:
  enabled: false
  replicas: 0

compactor:
  enabled: false

serviceMonitor:
  enabled: true
  interval: 30s
