# 최종 values.yaml for Minikube with MinIO (Simple Scalable 모드)
deploymentMode: SimpleScalable

grafana:
  enabled: false

# Simple Scalable 모드에서 사용할 컴포넌트들
backend:
  enabled: true
  replicas: 1
  securityContext:
    fsGroup: 10001
    runAsUser: 10001
    runAsGroup: 10001
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

read:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

write:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

# Distributed 모드 컴포넌트들 비활성화
distributor:
  enabled: false
  replicas: 0

ingester:
  enabled: false
  replicas: 0

querier:
  enabled: false
  replicas: 0

queryFrontend:
  enabled: false
  replicas: 0

compactor:
  enabled: false

# ==================== 변경된 부분 시작 ====================
# SimpleScalable 모드에서 기본으로 활성화되는 memcached 캐시의 리소스를 최소화합니다.
chunksCache:
    enabled: false
# ==================== 변경된 부분 끝 ====================


loki:
  distributor:
    ring:
      replication_factor: 1
  ingester:
    ring:
      replication_factor: 1
  useTestSchema: true
  limits_config:
    allow_structured_metadata: true
    retention_period: 7d
    ingestion_rate_mb: 5
    ingestion_burst_size_mb: 10
    max_entries_limit_per_query: 5000
    max_cache_freshness_per_query: 10m
    max_query_length: 168h
    max_query_parallelism: 16
    max_streams_per_user: 1000
    max_line_size: 128KB
    reject_old_samples: true
    reject_old_samples_max_age: 24h

  storage:
    type: 's3'
    bucketNames:
      chunks: "loki-chunks"
      ruler: "loki-ruler"
      admin: "loki-admin"
    s3:
      endpoint: "http://minio.minio.svc.cluster.local:9000"
      insecure: true
      accessKeyId: "minioadmin"
      secretAccessKey: "minioadmin123"
      s3ForcePathStyle: true

  serviceAccount:
    create: true
    annotations: {}

serviceMonitor:
  enabled: true
  interval: 30s
