singleBinary:
  enabled: true

# PV를 사용하지 않으므로 비활성화
persistence:
  enabled: false

# Loki 기본 설정
loki:
  # 단일 모드에서는 여기서 파일 시스템 스토리지를 사용하도록 설정
  storage:
    type: 'filesystem'
  limits_config:
    allow_structured_metadata: true
    retention_period: 7d
    ingestion_rate_mb: 5
    ingestion_burst_size_mb: 10
    max_entries_limit_per_query: 5000
    max_cache_freshness_per_query: 10m
    max_query_length: 168h
    max_query_parallelism: 16
    max_streams_per_user: 1000
    max_line_size: 128KB
    reject_old_samples: true
    reject_old_samples_max_age: 24h

# 분산 모드 컴포넌트 비활성화
distributor:
  enabled: false
ingester:
  enabled: false
querier:
  enabled: false

# 기타 비활성화 컴포넌트
grafana:
  enabled: false
compactor:
  enabled: false