loki:
  # 모든 설정을 loki 키 아래에 통합합니다.

  # 단일 모드 활성화
  singleBinary:
    enabled: true

  # PV 비활성화
  persistence:
    enabled: false

  # 스토리지 설정
  storage:
    type: 'filesystem'

  # 분산 모드 컴포넌트 비활성화
  distributor:
    enabled: false
  ingester:
    enabled: false
  querier:
    enabled: false

  # 기타 비활성화 컴포넌트
  compactor:
    enabled: false

# 이 차트의 Grafana는 사용하지 않음
grafana:
  enabled: false