# values-test.yaml 수정 제안

# 명시적으로 SingleBinary 모드 설정
deploymentMode: SingleBinary

# SingleBinary 모드 활성화 및 설정
singleBinary:
  enabled: true
  replicas: 1
  # 필요하다면 persistence 및 resources 설정 유지
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# gateway가 의도치 않게 생성되므로 명시적으로 비활성화
gateway:
  enabled: false

# SingleBinary 모드에서는 아래 컴포넌트들을 명시적으로 끌 필요가 없습니다.
# deploymentMode 설정이 이를 자동으로 처리합니다.
# backend, read, write, distributor, ingester 등의 replicas: 0 설정 모두 제거

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  # ... 나머지 loki 설정은 그대로 유지 ...
  ruler:
    # ruler API는 SingleBinary 모드에서 기본 비활성화되므로 이 설정이 문제를 일으킬 수 있습니다.
    # 우선 주석 처리하거나 제거하는 것을 권장합니다.
    # enable_api: false
    storage:
      local:
        directory: /tmp/loki/rules
    # wal 설정 등 나머지 부분은 유지
    wal:
      dir: /tmp/loki/ruler-wal

# 모니터링 컴포넌트 비활성화 설정은 그대로 유지
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false
  serviceMonitor:
    enabled: false
selfMonitoring:
  enabled: false
lokiCanary:
  enabled: false
grafanaAgent:
  installOperator: false