# values-test.yaml (최종 수정본)

# 1. 배포 모드 설정
deploymentMode: SingleBinary

# 2. SingleBinary 모드 활성화
singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ===================================================================
# ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ 모든 다른 컴포넌트 비활성화 ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
# ===================================================================
# 각 컴포넌트를 enabled: false 로 명확하게 비활성화합니다.
loki:
  # 이 loki 블록은 singleBinary 모드의 설정을 위한 것입니다.
  # storage_config, ruler 등은 여기에 유지합니다.
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    path_prefix: /tmp/loki
  storage:
    type: filesystem
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  ruler:
    storage:
      type: local
      local:
        directory: /tmp/loki/rules
    wal:
      dir: /tmp/loki/ruler-wal
  limits_config:
    allow_structured_metadata: true
    retention_period: 7d
    ingestion_rate_mb: 5
    ingestion_burst_size_mb: 10
    max_entries_limit_per_query: 5000

# 아래는 모두 마이크로서비스(simple scalable) 모드용 컴포넌트입니다.
# enabled: false로 설정하여 완전히 비활성화합니다.
write:
  enabled: false
read:
  enabled: false
backend:
  enabled: false

ingester:
  enabled: false
distributor:
  enabled: false
querier:
  enabled: false
queryFrontend:
  enabled: false
queryScheduler:
  enabled: false
compactor:
  enabled: false
gateway:
  enabled: false

# ===================================================================
# ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
# ===================================================================

# 모니터링 관련 부가 기능 비활성화
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false
  serviceMonitor:
    enabled: false
selfMonitoring:
  enabled: false
lokiCanary:
  enabled: false
grafanaAgent:
  installOperator: false