# values-test.yaml (수정 최종본)

deploymentMode: SingleBinary

singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# 의도치 않게 생성되는 gateway 명시적 비활성화
gateway:
  enabled: false

loki:
  auth_enabled: false
  # 공통 경로 접두사를 /tmp/loki로 설정
  commonConfig:
    replication_factor: 1
    path_prefix: /tmp/loki

  # 스토리지 타입을 filesystem으로 지정
  storage:
    type: filesystem

  # 스토리지 상세 설정에서 디렉터리를 명시적으로 /tmp/loki 하위로 지정
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks

  # ruler 설정에서 디렉터리 경로를 명시적으로 /tmp/loki 하위로 지정
  ruler:
    storage:
      type: local
      local:
        directory: /tmp/loki/rules
    wal:
      dir: /tmp/loki/ruler-wal

  # limits_config 등 나머지 설정은 기존과 동일하게 유지
  limits_config:
    allow_structured_metadata: true
    retention_period: 7d
    ingestion_rate_mb: 5
    ingestion_burst_size_mb: 10
    max_entries_limit_per_query: 5000
    # ... 기타 limits_config 설정 ...

# 모니터링 컴포넌트 비활성화
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false
  serviceMonitor:
    enabled: false
selfMonitoring:
  enabled: false
lokiCanary:
  enabled: false
grafanaAgent:
  installOperator: false