# values-test.yaml (수정 최종본)

deploymentMode: SingleBinary

# SingleBinary 모드 활성화
singleBinary:
  enabled: true
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ===================================================================
# ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼ 이 부분이 추가되었습니다 ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
# ===================================================================
# 마이크로서비스 모드 컴포넌트들을 명시적으로 비활성화(replicas: 0)합니다.
ingester:
  replicas: 0
distributor:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
compactor:
  replicas: 0
# ===================================================================
# ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲
# ===================================================================

# gateway는 이미 비활성화 되어 있었지만, 명확성을 위해 유지합니다.
gateway:
  enabled: false

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    path_prefix: /tmp/loki
  storage:
    type: filesystem
  storage_config:
    filesystem:
      directory: /tmp/loki/chunks
  ruler:
    storage:
      type: local
      local:
        directory: /tmp/loki/rules
    wal:
      dir: /tmp/loki/ruler-wal
  limits_config:
    allow_structured_metadata: true
    retention_period: 7d
    ingestion_rate_mb: 5
    ingestion_burst_size_mb: 10
    max_entries_limit_per_query: 5000

# 모니터링 컴포넌트 비활성화
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false
  serviceMonitor:
    enabled: false
selfMonitoring:
  enabled: false
lokiCanary:
  enabled: false
grafanaAgent:
  installOperator: false