apiVersion: v1
kind: Service
metadata:
  name: otel-metric-collector-headless
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: opentelemetry-metric-collector