logging:
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

## Default configurations
otel:
  traces:
    sampler:
      probability: 1
  springboot:
    web:
      enabled: true
    httpclients:
      enabled: true
    aspects:
      enabled: true
server:
  port: 8081