repositories:
  - name: minio
    url: https://operator.min.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: jetstack
    url: https://charts.jetstack.io

helmBinary: helm

helmDefaults:
  verify: false
  wait: false
  atomic: false
  timeout: 600

helmfiles:
  - path: helmfile/helmfile-test.yaml