apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server
  namespace: metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
  template:
    metadata:
      labels:
        app: spring-server
      annotations:
        instrumentation.opentelemetry.io/inject-java: "metric/otel-instrumentation"
        instrumentation.opentelemetry.io/container-names: "spring-server"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
    spec:
      containers:
      - name: spring-server
        image: spring-server:latest
        imagePullPolicy: Never
        env:
          # SigNoz Query Service로 직접 전송
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://signoz.metric.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_TRACES_EXPORTER
            value: "otlp"
          - name: OTEL_SERVICE_NAME
            value: "spring-server"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name=spring-server,service.version=1.0.0,deployment.environment=development"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-server
  namespace: metric
spec:
  type: ClusterIP
  selector:
    app: spring-server
  ports:
  - port: 8081
    name: app
    targetPort: 8081
  - port: 9464
    name: metric
    targetPort: 9464

