apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server
  namespace: metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
  template:
    metadata:
      labels:
        app: spring-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
        instrumentation.opentelemetry.io/inject-java: "otel/otel-instrumentation"
        instrumentation.opentelemetry.io/container-names: "spring-server"
    spec:
      containers:
        - name: spring-server
          image: spring-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 9464
              name: metrics
          env:
            # 명시적 서비스명 설정
            - name: OTEL_SERVICE_NAME
              value: "spring-server"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=spring-server,service.version=1.0.0,deployment.environment=development"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.metric.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
