apiVersion: v1
kind: Service
metadata:
  name: signoz-otlp
  namespace: metric
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
spec:
  type: ClusterIP
  ports:
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp-http
  selector:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: signoz
