releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.4
    createNamespace: true
    set:
      - name: installCRDs
        value: true
  - name: minio
    namespace: minio
    chart: minio/minio
    createNamespace: true
    set:
      - name: rootUser
        value: minioadmin
      - name: rootPassword
        value: minioadmin123
      - name: mode
        value: standalone
      - name: replicas
        value: 1
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/prometheus
    version: 25.8.0  # 최신 버전 사용 (필요시 조정)
    createNamespace: true
    values:
      - "../prometheus/values-test.yaml"
  - name: loki  # loki-stack → loki로 변경
    namespace: monitoring
    createNamespace: true
    chart: grafana/loki
    version: 6.30.1
    values:
      - "../loki/values-test.yaml"
    needs:
      - minio/minio
  - name: tempo
    namespace: monitoring
    chart: grafana/tempo
    version: 1.23.2
    values:
      - "../tempo/values-test.yaml"

  - name: opentelemetry-operator
    namespace: opentelemetry-operator-system
    chart: open-telemetry/opentelemetry-operator
    version: 0.90.4
    createNamespace: true
    needs:
      - cert-manager/cert-manager

  - name: opentelemetry-collector
    namespace: monitoring
    chart: open-telemetry/opentelemetry-collector
    version: 0.126.0
    values:
      - "../opentelemetry/collector/values-test.yaml"
    needs:
      - opentelemetry-operator-system/opentelemetry-operator
      - monitoring/loki
      - monitoring/tempo

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 8.3.4
    createNamespace: true
    needs:
      - monitoring/prometheus
      - monitoring/loki
      - monitoring/tempo
    values:
      - "../grafana/values-test.yaml"