releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.4
    createNamespace: true
    set:
      - name: installCRDs
        value: true
  - name: minio
    namespace: minio
    chart: minio/minio
    createNamespace: true
    set:
      - name: rootUser
        value: minioadmin
      - name: rootPassword
        value: minioadmin123
      - name: mode
        value: standalone
      - name: replicas
        value: 1
  # ▼▼▼▼▼ 1단계: Prometheus CRD만 설치하는 릴리스 (수정됨) ▼▼▼▼▼
  - name: kube-prometheus-stack-crds
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 56.5.0
    createNamespace: true
    values:
      - alertmanager:
          enabled: false
      - grafana:
          enabled: false
      - kube-state-metrics:
          enabled: false
      - prometheus-node-exporter:
          enabled: false
      - prometheusOperator:
          enabled: false
      - prometheus:
          enabled: false
      # ▼▼▼▼▼ 이 설정이 핵심입니다 ▼▼▼▼▼
      - defaultRules:
          create: false # PrometheusRule 리소스 생성을 비활성화
      - kubeEtcd:
          enabled: false
      - kubeControllerManager:
          enabled: false
      - kubeScheduler:
          enabled: false
      - kubeProxy:
          enabled: false

  # ▼▼▼▼▼ 2단계: 나머지 Prometheus 스택 설치 (수정됨) ▼▼▼▼▼
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 56.5.0
    createNamespace: true
    # 위에서 만든 values 파일을 사용합니다.
    values:
      - "../prometheus/values-test.yaml"
    # CRD 설치 릴리스가 끝난 후에 실행되도록 의존성을 설정합니다.
    needs:
      - monitoring/kube-prometheus-stack-crds
  - name: loki
    namespace: monitoring
    createNamespace: true
    chart: grafana/loki
    version: 6.30.1
    values:
      - "../loki/values-test.yaml"
    needs:
      - minio/minio
  - name: tempo
    namespace: monitoring
    chart: grafana/tempo
    version: 1.23.2
    values:
      - "../tempo/values-test.yaml"

  - name: opentelemetry-operator
    namespace: opentelemetry-operator-system
    chart: open-telemetry/opentelemetry-operator
    version: 0.90.4
    createNamespace: true
    needs:
      - cert-manager/cert-manager

  - name: opentelemetry-collector
    namespace: monitoring
    chart: open-telemetry/opentelemetry-collector
    version: 0.126.0
    values:
      - "../opentelemetry/collector/values-test.yaml"
    needs:
      - opentelemetry-operator-system/opentelemetry-operator
      - monitoring/loki
      - monitoring/tempo

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 8.3.4
    createNamespace: true
    needs:
      - monitoring/kube-prometheus-stack
      - monitoring/loki
      - monitoring/tempo
    values:
      - "../grafana/values-test.yaml"