apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-logback-config
  namespace: {{ .Values.app.namespace }}
data:
  logback.xml: |
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml" />
        
        <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
                <pattern>${CONSOLE_LOG_PATTERN}</pattern>
            </encoder>
        </appender>
        
        <logger name="TEST_LOGGER" level="TRACE" />
        <logger name="org.springframework.web" level="INFO"/>
        <logger name="org.hibernate.engine.internal.StatisticalLoggingSessionEventListener" level="OFF"/>
        <logger name="org.hibernate.engine.internal.StatefulPersistenceContext" level="ERROR"/>
        <logger name="reactor.netty.resources.PooledConnectionProvider" level="OFF"/>
        
        <root level="INFO">
            <appender-ref ref="CONSOLE" />
        </root>
    </configuration>
