apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: otel
spec:
  exporter:
    endpoint: http://opentelemetry-lb-collector.monitoring.svc.cluster.local:4317
  propagators:
    - tracecontext
    - b3
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://opentelemetry-lb-collector.monitoring.svc.cluster.local:4317
      - name: OTEL_METRICS_EXPORTER
        value: prometheus
      - name: OTEL_TRACES_SAMPLER
        value: always_on
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXEMPLAR_FILTER
        value: always_on
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
        value: http://opentelemetry-lb-collector.monitoring.svc.cluster.local:4317
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://opentelemetry-lb-collector.monitoring.svc.cluster.local:4317
