# OpenTelemetry Operator 기본 설정
replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# 추가 Kubernetes 리소스 생성
extraObjects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: otel

  - apiVersion: opentelemetry.io/v1alpha1
    kind: Instrumentation
    metadata:
      name: otel-instrumentation
      namespace: otel
    spec:
      exporter:
        endpoint: http://opentelemetry-collector.monitoring.svc.cluster.local:4317
      propagators:
        - tracecontext
        - baggage
        - b3
      sampler:
        type: always_on
      java:
        image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.8.0
        env:
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://opentelemetry-collector.monitoring.svc.cluster.local:4317
          - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
            value: "false"
          - name: OTEL_JAVAAGENT_ENABLED
            value: "true"
      nodejs:
        image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.56.0
      python:
        image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.48b0
