mode: deployment

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 80
      spike_limit_percentage: 25
    batch:
      send_batch_size: 2048
      timeout: 10s
      send_batch_max_size: 4096
    k8sattributes:
      auth_type: "serviceAccount"
      passthrough: true
      extract:
        metadata:
          - k8s.pod.name
          - k8s.namespace.name
          - k8s.container.name
          - k8s.deployment.name

  # connectors를 별도 섹션으로 분리
  connectors:
    spanmetrics:
      histogram:
        explicit:
          buckets: [0.5, 0.75, 1, 2.5, 5, 10]
      dimensions:
        - name: k8s.namespace.name
        - name: k8s.deployment.name
      metrics_flush_interval: 15s

  exporters:
    debug:
      verbosity: detailed
    loki:
      endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
    # tempo exporter를 otlp로 변경
    otlp/tempo:
      endpoint: "http://tempo-distributor.monitoring.svc.cluster.local:4318"
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [otlp/tempo, spanmetrics, debug]  # spanmetrics를 connector로 사용
      logs:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [loki, debug]
      metrics:
        receivers: [spanmetrics]  # connector에서 메트릭 수신
        processors: [batch]
        exporters: [debug]
