mode: deployment

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 80
      spike_limit_percentage: 25
    batch:
      send_batch_size: 2048
      timeout: 10s
      send_batch_max_size: 4096
    k8sattributes:
      auth_type: "serviceAccount"
      passthrough: true
    resource:
      attributes:
        # 모든 k8s 관련 속성 제거하고 필요한 것만 유지
        - key: deployment_name
          from_attribute: k8s.deployment.name
          action: upsert
        - key: service_name
          from_attribute: service.name
          action: upsert
        # 기존 k8s 속성들 모두 삭제
        - key: k8s.deployment.name
          action: delete
        - key: k8s.pod.name
          action: delete
        - key: k8s.namespace.name
          action: delete
        - key: k8s.container.name
          action: delete
        - key: k8s.replicaset.name
          action: delete
        - key: k8s.node.name
          action: delete
        - key: k8s.pod.ip
          action: delete

  # connectors를 별도 섹션으로 분리
  connectors:
    spanmetrics:
      histogram:
        explicit:
          buckets: [0.5, 0.75, 1, 2.5, 5, 10]
      dimensions:
        - name: deployment_name  # k8s.namespace.name 제거
        - name: service_name     # k8s.deployment.name 대신 service_name 사용
      metrics_flush_interval: 15s

  exporters:
    debug:
      verbosity: detailed
    otlphttp:
      endpoint: "http://loki-gateway.monitoring.svc.cluster.local/otlp"
      tls:
        insecure: true
    otlp/tempo:
      endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [otlp/tempo, spanmetrics, debug]  # spanmetrics를 connector로 사용
      logs:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [otlphttp, debug]
      metrics:
        receivers: [spanmetrics]  # connector에서 메트릭 수신
        processors: [batch]
        exporters: [debug]
