mode: deployment

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 80
      spike_limit_percentage: 25
    batch:
      send_batch_size: 2048
      timeout: 10s
      send_batch_max_size: 4096
    k8sattributes:
      auth_type: "serviceAccount"
      passthrough: true
    metricstransform:
      transforms:
        # 'traces.span.metrics.calls' -> 'traces_spanmetrics_calls_total'
        - include: traces.span.metrics.calls
          action: update
          new_name: traces_spanmetrics_calls_total
        # 'traces.span.metrics.duration' -> 'traces_spanmetrics_latency'
        # (_bucket, _count, _sum 접미사는 exporter가 자동으로 추가해 줌)
        - include: traces.span.metrics.duration
          action: update
          new_name: traces_spanmetrics_latency
    resource:
      attributes:
        # 필수 속성들 유지
        - key: service.instance.id
          from_attribute: k8s.pod.name
          action: upsert
        - key: deployment.environment.name
          value: "production"  # 또는 적절한 환경 값
          action: upsert

        # 기존 설정 유지
        - key: deployment_name
          from_attribute: k8s.deployment.name
          action: upsert
        - key: service_name
          from_attribute: service.name
          action: upsert

  connectors:
    spanmetrics:
      namespace: traces.spanmetrics
      histogram:
        explicit:
          buckets: [ 0.5, 0.75, 1, 2.5, 5, 10 ]
      dimensions:
        - name: service.name
        - name: span.name
        - name: http.route
        - name: http.method
        - name: status.code
        - name: k8s.deployment.name
      metrics_flush_interval: 15s
      exemplars:
        enabled: true

  exporters:
    debug:
      verbosity: detailed
    otlphttp:
      endpoint: "http://loki-gateway.monitoring.svc.cluster.local/otlp"
      tls:
        insecure: true
    otlp/tempo:
      endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    prometheusremotewrite:
      endpoint: "http://prometheus-server.monitoring.svc.cluster.local:80/api/v1/write"


  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, resource, batch]
        exporters: [otlp/tempo, spanmetrics, debug]  # spanmetrics를 connector로 사용
      logs:
        receivers: [otlp]
        processors: [memory_limiter, k8sattributes, resource, batch]
        exporters: [otlphttp, debug]
      metrics:
        receivers: [spanmetrics]  # connector에서 메트릭 수신
        processors: [batch, metricstransform]
        exporters: [prometheusremotewrite, debug]
